### ISSUE TITLE
No connection listener set to handle message received from the server. Test on TB2.1.0, How to adjust conf

### ISSUE THREAD

**Issue by ten2net** [thingsboard/performance-tests#19]
```shell
Exception in thread "hawtdispatch-DEFAULT-7" java.lang.IllegalStateException: No connection listener set to handle message received from the server.
        at org.fusesource.mqtt.client.CallbackConnection.createListenerNotSetError(CallbackConnection.java:951)
        at org.fusesource.mqtt.client.CallbackConnection.access$000(CallbackConnection.java:73)
        at org.fusesource.mqtt.client.CallbackConnection$1.onPublish(CallbackConnection.java:96)
        at org.fusesource.mqtt.client.CallbackConnection.toReceiver(CallbackConnection.java:911)
        at org.fusesource.mqtt.client.CallbackConnection.processFrame(CallbackConnection.java:808)
        at org.fusesource.mqtt.client.CallbackConnection.access$1700(CallbackConnection.java:73)
        at org.fusesource.mqtt.client.CallbackConnection$6.onTransportCommand(CallbackConnection.java:425)
        at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:713)
        at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592)
        at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
        at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
        at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
```

**Comment by ten2net** [comment]
```
restUrl=http://192.168.8.23
mqttUrls=tcp://192.168.8.23:1883
deviceCount=350
publishTelemetryCount=60
publishTelemetryPause=1000
username=tenantt@thingsboard.org
password=tenant
```

**Comment by GuaKin-Huang** [comment]
please，How solve this question？？？？

**Comment by GuaKin-Huang** [comment]
please，How solve this question？？？？

**Comment by GuaKin-Huang** [comment]
please，How to solve this question？？？？

**Comment by denniedeng** [comment]
i have the same problem when i doing stress Testing!
in the same environment, i use version 1.4 not this problem.
why?

**Comment by smatvienko-tb** [comment]
Hey, guys!
It looks this topic is a little bit outdated. The latest version is 3.3.2. Please, try the latest version.
