### ISSUE TITLE
Error while launching the docker image

### ISSUE THREAD

**Issue by miraj** [thingsboard/performance-tests#28]
See below the error while I run : 
docker run -it --env-file .env --rm --name tb-perf-test thingsboard/tb-performance-test

19:14:19.266 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: or
g.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultRestClientService': Invocation of init method failed; nested exception is o
rg.springframework.web.client.HttpClientErrorException: 401 null
19:14:19.270 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
19:14:19.288 [main] INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer -

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
19:14:19.296 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultRestClientService': Invocation of init method failed; nested exception is
 org.springframework.web.client.HttpClientErrorException: 401 null
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.ja
va:137)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.j
ava:409)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)

What could be the reason for the failure?

**Comment by smatvienko-tb** [comment]
Hi, @miraj 
It looks like 401 (Unauthorized) issues. Please, check the user and password.
```
REST_USERNAME=tenant@thingsboard.org
REST_PASSWORD=tenant
```
